### ISSUE TITLE
start winium driver through command prompt gives Argument exception

### ISSUE THREAD

**Issue by skmvali** [2gis/Winium.Desktop#118]
D:\>Winium.Desktop.Driver.exe

Unhandled Exception: System.ArgumentException: LayoutRenderer cannot be found: '
longdate'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory con
figurationItemFactory, SimpleStringReader sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configura
tionItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Targets.TargetWithLayout..ctor()
   at Winium.Desktop.Driver.Logger.TargetConsole(Boolean verbose)
   at Winium.Desktop.Driver.Program.Main(String[] args)

**Comment by NickAb** [comment]
What versions of .NET framework do you have installed, do you have 4.5 installed?

**Comment by skmvali** [comment]
when i fired the command first time..i was asked to install 4.0 Version ..installed 4.0

**Comment by skmvali** [comment]
i tried 4.6 and able to start successfully ..thanks for helping the issue.

**Comment by NickAb** [comment]
Requirements state that 4.5.1 is required https://github.com/2gis/Winium.Desktop#requirements.

Where you prompted to install .NET Framework 4.0 by OS when running the driver for the first time?

**Comment by skmvali** [comment]
correct first time prompted me to install 4.0
