### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by rajeevrdyk** [2gis/Winium.Desktop#154]
18:50:22 [FATAL] Failed to start driver: System.NullReferenceException: Object reference not set to an instance of an object.
   at Winium.Desktop.Driver.Listener.HandleRequest(HttpRequest acceptedRequest)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

**Comment by rajeevrdyk** [comment]
Just tried to launch a Calculator app using Winium and observed above crash

**Comment by alexandis** [comment]
I join here to confirm the same error. Here is the log:

> PLATFORM VERSION INFO
> 	Windows 			: 10.0.15063.0 (Win32NT)
> 	Common Language Runtime 	: 4.0.30319.42000
> 	System.Deployment.dll 		: 4.7.2046.0 built by: NET47REL1
> 	clr.dll 			: 4.7.2046.0 built by: NET47REL1
> 	dfdll.dll 			: 4.7.2046.0 built by: NET47REL1
> 	dfshim.dll 			: 10.0.15063.0 (WinBuild.160101.0800)
> 
> SOURCES
> 	Deployment url			: https://github-windows.s3.amazonaws.com/GitHub.application
> 						Server		: AmazonS3
> 	Application url			: https://github-windows.s3.amazonaws.com/Application%20Files/GitHub_3_3_4_0/GitHub.exe.manifest
> 						Server		: AmazonS3
> 
> IDENTITIES
> 	Deployment Identity		: GitHub.application, Version=3.3.4.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86
> 	Application Identity		: GitHub.exe, Version=3.3.4.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86, type=win32
> 
> APPLICATION SUMMARY
> 	* Installable application.
> 	* Trust url parameter is set.
> ERROR SUMMARY
> 	Below is a summary of the errors, details of these errors are listed later in the log.
> 	* Activation of https://github-windows.s3.amazonaws.com/GitHub.application resulted in exception. Following failure messages were detected:
> 		+ Downloading https://github-windows.s3.amazonaws.com/Application Files/GitHub_3_3_4_0/d3dcompiler_47.dll.deploy did not succeed.
> 		+ Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
> 		+ An existing connection was forcibly closed by the remote host
> 
> COMPONENT STORE TRANSACTION FAILURE SUMMARY
> 	No transaction error was detected.
> 
> WARNINGS
> 	There were no warnings during this operation.
> 
> OPERATION PROGRESS STATUS
> 	* [06.05.2017 0:28:54] : Activation of https://github-windows.s3.amazonaws.com/GitHub.application has started.
> 	* [06.05.2017 0:28:55] : Processing of deployment manifest has successfully completed.
> 	* [06.05.2017 0:28:55] : Installation of the application has started.
> 	* [06.05.2017 0:28:56] : Processing of application manifest has successfully completed.
> 	* [06.05.2017 0:28:59] : Found compatible runtime version 4.0.30319.
> 	* [06.05.2017 0:28:59] : Request of trust and detection of platform is complete.
> 
> ERROR DETAILS
> 	Following errors were detected during this operation.
> 	* [06.05.2017 0:34:33] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
> 		- Downloading https://github-windows.s3.amazonaws.com/Application Files/GitHub_3_3_4_0/d3dcompiler_47.dll.deploy did not succeed.
> 		- Source: System.Deployment
> 		- Stack trace:
> 			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
> 			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
> 			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
> 			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
> 			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
> 			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> --- End of stack trace from previous location where exception was thrown ---
> 			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> 			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
> 		--- Inner Exception ---
> 		System.IO.IOException
> 		- Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
> 		- Source: System
> 		- Stack trace:
> 			at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
> 			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
> 		--- Inner Exception ---
> 		System.Net.Sockets.SocketException
> 		- An existing connection was forcibly closed by the remote host
> 		- Source: System
> 		- Stack trace:
> 			at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
> 			at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
> 
> COMPONENT STORE TRANSACTION DETAILS
> 	No transaction information is available.
> 
> 
>

**Comment by heilwood** [comment]
Winium launched as admin?
