### ISSUE TITLE
I am automating UIpath Studio application.Unable to get text from windows based Dailog 

### ISSUE THREAD

**Issue by abhishake7354** [2gis/Winium.Desktop#202]
My code is  ::---

              wait.until(ExpectedConditions.alertIsPresent());
	      WebElement ele= getWebElement(By.name("Workflow Exception"));
		Alert alert=driver.switchTo().alert();
	          String salert=alert.getText();

Exception :::::::::::------------------

org.openqa.selenium.UnsupportedCommandException: 'getAlertText' is not valid or implemented command. (WARNING: The server did not provide any stacktrace information)

Driver info: org.openqa.selenium.winium.WiniumDriver

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1007)
	at org.openqa.selenium.support.ui.ExpectedConditions$28.apply(ExpectedConditions.java:837)
	at org.openqa.selenium.support.ui.ExpectedConditions$28.apply(ExpectedConditions.java:833)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.purple.bot.BaseClass.getDailogText(BaseClass.java:98)
	at com.purple.bot.test.AppTest.waitForPopUp(AppTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

![capture](https://user-images.githubusercontent.com/33840705/33031605-caf77a94-ce44-11e7-8a30-7814245262d0.PNG)

**Comment by abhishake7354** [comment]
How to read text data in the dailog box?

**Comment by rahulbommanaboina** [comment]
Use get attribute and check , if you are able to retrieve information
