### ISSUE TITLE
Winium doesn't work properly on Windows 10

### ISSUE THREAD

**Issue by RomanIovlev** [2gis/Winium.Desktop#213]
For example this simple Windows Calculator test doesn't work on Windows 10
See example here: https://github.com/Supreme85/jdi-desktop-example/blob/master/src/test/java/org/mytests/tests/example/PureWinium.java
e.g. winiumTest1()

First click on 7 done correctly but all other clicks misplaced on similar position right-bottom
Misplacement depends on left-top app corner position

**Comment by vinuthamikkilineni** [comment]
Hey Even i was facing the same problem .you have change the screen scaling to 100% then only it works.

**Comment by RomanIovlev** [comment]
How I can do this programmatically? Can you provide some example? (better in example above)
Thanks!

**Comment by Jyothish77** [comment]
I am facing similar issue. The screen scaling is 100% and  the control is identified using the AutomationID for the WPF application. But while running application the click is not happening on the identified control.

**Comment by Jyothish77** [comment]
The clicking is working as expected for me after updating the Windows10 OS Version from 1607 to 1709

**Comment by vinuthamikkilineni** [comment]
I have fixed this issue in Winium Crutius code in my local machine. i need to raise a pull request for the same. Now it works on all VMs ,Windows machine without changing your resolution

**Comment by vinuthamikkilineni** [comment]
I have raised pull request. i will update this thread as soon as it gets merged

**Comment by roopaturlapati** [comment]
waiting for your reply @vinuthamikkilineni ., please update .

**Comment by vinuthamikkilineni** [comment]
i have raised the pull request on winium crutius. its says still pending.

**Comment by vinuthamikkilineni** [comment]
https://github.com/2gis/Winium.Cruciatus/pull/75 is the link for pull request.

**Comment by vinuthamikkilineni** [comment]
you can pull the code from here https://github.com/vinuthamikkilineni/Winium.Cruciatus. build WiniumCrutius and add it as external reference for Winium desktop driver. It works

**Comment by ChaoLiou** [comment]
@vinuthamikkilineni 
still same ;-(
Do I need to change resolution settings with your version?

**Comment by vinuthamikkilineni** [comment]
@ChaoLiou ,
Nope
There is no need of changing resolution settings. Have you build Winium Desktop driver with new Winium Cruciatus.

**Comment by vinuthamikkilineni** [comment]
I can upload the Winium.Desktop.Driver.exe with all those changes

**Comment by Schroet** [comment]
Hey guys! Are there any changes here?

**Comment by ghost** [comment]
@vinuthamikkilineni Please do so if you're able to <3

**Comment by vinuthamikkilineni** [comment]
hey Its working for me. I am using it for our UI Automation

**Comment by bhaskaralluri** [comment]
@vinuthamikkilineni : Could you please upload the exe file with fix ? I am using Windows 10, Even though i gave everything correct ( automation id's for the text boxes ), it is not clicking on it to type, but i noticed mouse movement on the screen do not know why. Hopefully all these are related to scaling issues and your .exe  driver will fix it. thank you.

**Comment by ankurb9** [comment]
I faced same issue... How I resolved this is I used below lines to start the service .

WiniumDriverService service = new WiniumDriverService.Builder()
				.usingDriverExecutable(new File(System.getProperty("user.dir")+"\\Drivers\\Winium.Desktop.Driver-1.6.exe"))
				.usingPort(9999)
				.withVerbose(true)
				.withSilent(false)
				.buildDesktopService();	
	service.start();
WiniumDriver driver = new WiniumDriver(service,opt);

After that You need to stop and start the service for each command. it worked like charm for me.

Remember you need to start only one service at a time otherwise you will get socketexception.
service.start();
service.start();
**is incorrect.**

service.start();
service.stop()
service.start();
**this is correct**

e.g." 
**you have already started the service post initialisation so no need to start again**
driver.findelement(by.id(**)).click();
service.strop();

service.start();
driver.findelement(by.id(**)).click();
service.stop();

**Comment by carlosEnriqueGosalbez** [comment]
Hello, when I try to automate the calculator, the first click does it right but the rest clicks randomly. Someone has the solution. I have the resolution 100% connected with VGA.
Thanks

**Comment by vinuthamikkilineni** [comment]
> I faced same issue... How I resolved this is I used below lines to start the service .
> 
> WiniumDriverService service = new WiniumDriverService.Builder()
> .usingDriverExecutable(new File(System.getProperty("user.dir")+"\Drivers\Winium.Desktop.Driver-1.6.exe"))
> .usingPort(9999)
> .withVerbose(true)
> .withSilent(false)
> .buildDesktopService();
> service.start();
> WiniumDriver driver = new WiniumDriver(service,opt);
> 
> After that You need to stop and start the service for each command. it worked like charm for me.
> 
> Remember you need to start only one service at a time otherwise you will get socketexception.
> service.start();
> service.start();
> **is incorrect.**
> 
> service.start();
> service.stop()
> service.start();
> **this is correct**
> 
> e.g."
> **you have already started the service post initialisation so no need to start again**
> driver.findelement(by.id(**)).click();
> service.strop();
> 
> service.start();
> driver.findelement(by.id(**)).click();
> service.stop();



> @vinuthamikkilineni : Could you please upload the exe file with fix ? I am using Windows 10, Even though i gave everything correct ( automation id's for the text boxes ), it is not clicking on it to type, but i noticed mouse movement on the screen do not know why. Hopefully all these are related to scaling issues and your .exe driver will fix it. thank you.

I am attaching a zip file built locally. Please note my pull request is not approved by Winium team . so It cannot be actual released driver

**Comment by vinuthamikkilineni** [comment]
[Winium.Desktop.Driver.exe.zip](https://github.com/2gis/Winium.Desktop/files/2851515/Winium.Desktop.Driver.exe.zip)

**Comment by vinuthamikkilineni** [comment]
> I faced same issue... How I resolved this is I used below lines to start the service .
> 
> WiniumDriverService service = new WiniumDriverService.Builder()
> .usingDriverExecutable(new File(System.getProperty("user.dir")+"\Drivers\Winium.Desktop.Driver-1.6.exe"))
> .usingPort(9999)
> .withVerbose(true)
> .withSilent(false)
> .buildDesktopService();
> service.start();
> WiniumDriver driver = new WiniumDriver(service,opt);
> 
> After that You need to stop and start the service for each command. it worked like charm for me.
> 
> Remember you need to start only one service at a time otherwise you will get socketexception.
> service.start();
> service.start();
> **is incorrect.**
> 
> service.start();
> service.stop()
> service.start();
> **this is correct**
> 
> e.g."
> **you have already started the service post initialisation so no need to start again**
> driver.findelement(by.id(**)).click();
> service.strop();
> 
> service.start();
> driver.findelement(by.id(**)).click();
> service.stop();

Starting the service and stoping the service for every click means Starting a new connection for every operation that will be heavy on process. It will slowdown your overall performance

**Comment by Devil1061** [comment]
While trying to launch Winium.driver.exe socket exception has occurred. Below is the detailed message.

Starting Windows Desktop Driver on port 9999

15:19:56 [FATAL] Failed to start driver: System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

I am using windows 10 OS. It is just working fine in the system which is running on Windows 7.

Can anyone suggest me to overcome the issue I am facing?

**Comment by vinuthamikkilineni** [comment]
Its because port 9999 is being used by another process

**Comment by Devil1061** [comment]
Thanks @vinuthamikkilineni, tried running it in different port and it worked.

**Comment by Shubham12Baid** [comment]
> [Winium.Desktop.Driver.exe.zip](https://github.com/2gis/Winium.Desktop/files/2851515/Winium.Desktop.Driver.exe.zip)

Hi @vinuthamikkilineni 
I tried using this version of the driver to automate a custom application. However this driver is still giving the same issue as the previous one. It is still identifying and clicking a distance in the right down direction away from the actual position of the element. This driver along with the winium driver from the official site both work fine when zoom setting is set to 150% at 1920x1080 resolution. Yeah its not working for me at 100 % zoom. if u have any suggestions to correct this from the code itself insteadd of manually changing the zoom setting every time, pls help

**Comment by v3g3t4x** [comment]
Same issue. Don't works...
p.s.: Winium latest commit was 3 years ago. The project is dead?

**Comment by vinuthamikkilineni** [comment]
https://github.com/2gis/Winium.Cruciatus/pull/75 here is my pull request link where I made changes. You can take look and build it locally

**Comment by vinuthamikkilineni** [comment]
Sorry I was busy I ll check it on my local and update if I added wrong build

**Comment by MumtazRashid** [comment]
I am using winium of version 0.1.0-1, My test cases are failing for desktop application if screen resolution get changed and also if application get minimized, Is there any way around we can handle such cases ?

**Comment by MumtazRashid** [comment]
@Shubham12Baid  I have used your exe for winium but still if i change resolution of my screen, Test cases are failing for desktop application, It is clicking somewhere else not at the specified locator with its id

**Comment by Shubham12Baid** [comment]
> @Shubham12Baid I have used your exe for winium but still if i change resolution of my screen, Test cases are failing for desktop application, It is clicking somewhere else not at the specified locator with its id

HI @MumtazRashid The exe posted in the comment is not posted by me but by @vinuthamikkilineni  .This problem with resolution cannot be resolved until the devs of winium provide update because many applications require you to login into windows after changing the resolution for the change to be effective. Thus even if you manually or through a script change the resolution to 100%, unless you re login into windows the app would still run in its previous resolution configuration. There is no fix up untill now for this. :(
