### ISSUE TITLE
Winium Window Handle

### ISSUE THREAD

**Issue by Abhishekkawathekar** [2gis/Winium.Desktop#218]
Hi Team,

I am automating the window application using Java.
I am opening multiple window through click button in my windows desktop application. I wanted to switch the window. But, the issue is the widnow handle which i am getting is not constant. Like I have one search button which open another window in application. I was thinking of utilizing the switch command with for loop but it was not working. So i just printed the values of window handle in console. And the issue was the window handle before clicking the button is not present when I am getting the list of window handles after clicking the button. I think this is the issue with switch command is not working.
But this may be the misleading information.

So, I have attached the code and the output for your quick reference.
Hoping for the positive resolution.

Java Code
		String BeforeHandle = driver.getWindowHandle();
		System.out.println(BeforeHandle);
		driver.findElement(By.id("Button_ID")).click();
		Thread.sleep(2000);
		Set<String> Handles = driver.getWindowHandles();
		System.out.println("Available Window Handles are " + Handles);

Console Output
524394
Available Window Handles are [263996, 198876]

**Comment by amod-thakur** [comment]
@Abhishekkawathekar ,
Try the following code to get the window handle of the window you want to switch to.

```
WebElement newWindow = driver.findElement(By.name("Name attribute of the window"));
String newWindowHandle = newWindow.getAttribute("NativeWindowHandle");
driver.switchTo().window(newWindowHandle);
```

**Comment by Abhishekkawathekar** [comment]
Hi @Chintzz 
I have tried the code you have suggested here but the issue is that is returning the null value for windowhandle in the string. When, I investigated it further I can see that even NativeWindowHandle is not the constant with my application. So I have tried with following code.

WebElement newWindow = driver.findElement(By.name("Sales And CRM Employees"));
		System.out.println("New window found"+newWindow);
		
		String newWindowHandle = newWindow.getTagName();
		System.out.println("New windowhandle found is "+newWindowHandle);

But after using this code I am getting following error.

org.openqa.selenium.WebDriverException: An unknown error occurred in the remote end while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:899)
	at com.Winium_Cucumber.Automation_Test_Cases.Login_Test.LoginERP(Login_Test.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Also below is the information on Winappdriver

==========================================
POST /session/15B25D45-BD5B-4975-888C-A72484DBDBA4/element HTTP/1.1
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 59
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)

{
  "using": "name",
  "value": "Sales And CRM Employees"
}
HTTP/1.1 200 OK
Content-Length: 96
Content-Type: application/json

{"sessionId":"15B25D45-BD5B-4975-888C-A72484DBDBA4","status":0,"value":{"ELEMENT":"42.1053224"}}


==========================================
GET /session/15B25D45-BD5B-4975-888C-A72484DBDBA4/element/42.1053224/name HTTP/1.1
Accept-Encoding: gzip
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)


HTTP/1.1 200 OK
Content-Length: 92
Content-Type: application/json

{"sessionId":"15B25D45-BD5B-4975-888C-A72484DBDBA4","status":0,"value":"ControlType.Window"}


==========================================
POST /session/15B25D45-BD5B-4975-888C-A72484DBDBA4/window HTTP/1.1
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 34
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)

{
  "name": "ControlType.Window"
}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

**Comment by PritamGit** [comment]
@Abhishekkawathekar,

In Winium, what I observed is that getWindowHandles() gives only child windows handle. The window handle string (which is in decimal) is constant for a session but it may changes in another session. You can try switching to desire child window by passing the window handle string, but before switching get the window handle of the parent so you can switch back to parent after desire actions are performed on the selected child window.
