### ISSUE TITLE
Access is denied (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by Paravoffka** [2gis/Winium.Desktop#239]
Hello, I'm trying to use Winium to automate one Desktop app, but I've got a problem: 
When I click a button, it throws following error message: 
________________________________________________________________
Exception in thread "main" org.openqa.selenium.WebDriverException: Access is denied (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'richardwin7', ip: '10.0.1.120', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.winium.WiniumDriver
Capabilities [{app=C:\Program Files (x86)\Wenco\MDT5\MDT5.exe, args=, innerPort=9998, debugConnectToRunningApp=false, keyboardSimulator=1, launchDelay=0, platform=ANY}]
Session ID: AwesomeSession
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at testcases.MDT5Routine.main(MDT5Routine.java:25)
__________________________________________
The code is very basic: 
package testcases;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.winium.DesktopOptions;
import org.openqa.selenium.winium.WiniumDriver;

public class MDT5Routine {
	public static void main (String[] args) throws MalformedURLException, InterruptedException{
		DesktopOptions option = new DesktopOptions();
		option.setApplicationPath("C:\\Program Files (x86)\\Wenco\\MDT5\\MDT5.exe");
		WiniumDriver driver = new WiniumDriver(new URL ("http://localhost:9999"), option);
		Thread.sleep(10000);
	 
		driver.findElementByName("Badge In...").click();
	}
}
But if I don't click element and run just driver.findElementByName("Badge In..."); Script succeeded. 
What I'm doing wrong, or maybe it is designed that way I can't use automation tools? 
____________________________
Can it be triggered by this dialog box which I see when start program? 
![untitled2](https://user-images.githubusercontent.com/35976678/41073080-5f6c36e4-69b6-11e8-97ab-c4c13117186f.png)

______________________
Thanks.

**Comment by rateebhatt** [comment]
yes please login with admin when you run the automation 
or try this 
Click the “Start” orb, then type “UAC” in the Start Search box.
The result of “Change User Account Control settings” should appear at the top of the area. Select it.
Click “Yes” if a dialog appears.
You can choose Never Notify

**Comment by Paravoffka** [comment]
Hi rateebhatt, 
It's resolved the problem, you've been very helpful.
Thanks a lot!
