### ISSUE TITLE
FileNotFound Exception System.Security.Permissions

### ISSUE THREAD

**Issue by djinc3ption** [2gis/Winium.Desktop#252]
Hey all,

I have written some simple code to try and get my feet wet with Winium.

using OpenQA.Selenium.Winium;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Winium Test Code....");
            try
            {
                var service = WiniumDriverService.CreateDesktopService(@"C:\winium");
                var options = new DesktopOptions { ApplicationPath = @"C:\winium\b.exe" };
                WiniumDriver windriver = new WiniumDriver(service, options);

                windriver.FindElementById("ListViewSubItem-0").Click();
                Console.ReadKey();
            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception thrown : " + ex);
            }

        }
    }
}

However, when I try and run the program, it throws the following exception:

Exception thrown : System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration()
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at OpenQA.Selenium.Remote.Command.get_ParametersAsJsonString()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Winium.WiniumDriverCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Winium.WiniumDriver..ctor(WiniumDriverService service, IWiniumOptions options)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Agilent Anechoic\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 15

I installed the Winium service through NuGet Package Manager.  I have also tried opening VS as admin, setting permissions on the files and folders that I am trying to access, and rewriting the code a few different ways.  Always the same exception.  Has anyone seen this issue before?  Any help would be appreciated.

**Comment by djinc3ption** [comment]
Hey guys, 

I fixed the issue by using NuGet to download the System.Security.Permissions and added it as a reference.

**Comment by jr-jesse123** [comment]
solved for me as well

**Comment by himanshunegi1987** [comment]
In my case, it was a problem with the way I installed Newton.Json package.
I un-installed & re-installed the package and it did the trick.

**Comment by OneBobone** [comment]
> In my case, it was a problem with the way I installed Newton.Json package.
> I un-installed & re-installed the package and it did the trick.

Could you expand on that?
