### ISSUE TITLE
Unable to start Winium Driver

### ISSUE THREAD

**Issue by souravkumarsarkar** [2gis/Winium.Desktop#261]
Hi 
I'm using below code to initiate driver 
WiniumDriverService service = new WiniumDriverService.Builder()
                    .usingDriverExecutable(new File("path to driver.exe"))
                            .usingPort(8095)
                            .withVerbose(true)
                            .withSilent(false)
                            .buildDesktopService();

WiniumDriver driver = new WiniumDriver(service,options);

Though I'm using port 8095 but its always start on port 9999 and gives the below error. I'm able to use it by manually starting the driver but as per my automation requirement i need to start it automatically.

Error Trace :
Starting Windows Desktop Driver on port 9999

13:59:59 [DEBUG] Waiting for a connection...
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'HYDHTC151290L', ip: '10.64.101.4', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_111'
Driver info: driver.version: WiniumDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.winium.WiniumDriver.<init>(WiniumDriver.java:75)
	at imageprocessing.notepad.process(notepad.java:43)
	at imageprocessing.app.main(app.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:76)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:171)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:185)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:177)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
	at org.openqa.selenium.winium.WiniumDriverCommandExecutor.execute(WiniumDriverCommandExecutor.java:72)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 11 more

**Comment by shyam5674** [comment]
@souravkumarsarkar : Can you try removing that verbose and silent from the code.
Also before creating the winiumDriver, try to start the service like:

service.start(); //Build and Start a Winium Driver service

**Comment by souravkumarsarkar** [comment]
Hi @shyam5674 

Still the same issue after removing verbose, silent and adding service.start();

**Comment by nikita1307** [comment]
I am also facing the same issue... Any leads?

**Comment by Devil1061** [comment]
When I am trying to launch Winium.driver.exe from a windows 10 machine I am getting the below exception.

Starting Windows Desktop Driver on port 9999

15:51:31 [FATAL] Failed to start driver: System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

Is there anyway to overcome this issue? Am I missing something in setting up environment ?

**Comment by hillmae528** [comment]
Im experiencing this issue on an older(ish) win7 machine. Even manually trying to start the driver by running it as an application from file explorer isn't working. the window comes up saying that it is starting, but the process never actually starts? Is there some pre req I'm missing to just run the driver?
