### ISSUE TITLE
Drag & Drop not working in Desktop application

### ISSUE THREAD

**Issue by javawinium** [2gis/Winium.Desktop#329]
while using drag& drop in my desktop application , getting following error
could someone help me on this 

Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: 'mouseDown' is not valid or implemented command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'mccukswtstdc01', ip: '192.168.97.38', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.7'
Driver info: org.openqa.selenium.winium.WiniumDriver
Capabilities [{app=C:\IPR\Intergraph.Pr.Cockpit.exe, args=, innerPort=9998, debugConnectToRunningApp=false, keyboardSimulator=1, launchDelay=0, platform=ANY}]
Session ID: AwesomeSession
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:33)
at org.openqa.selenium.remote.RemoteMouse.mouseDown(RemoteMouse.java:77)
at org.openqa.selenium.interactions.ClickAndHoldAction.perform(ClickAndHoldAction.java:42)
at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
at OPRTest.OrgChart.main(OrgChart.java:67)

**Comment by DavidPurdy1** [comment]
@javawinium It is because it is not implemented in Winium. You could maybe try doing something like this?
https://github.com/2gis/Winium.Desktop/pull/73

**Comment by javawinium** [comment]
Thanks David
