### ISSUE TITLE
Drag and drop action 

### ISSUE THREAD

**Issue by DenUlyanov** [2gis/Winium.Desktop#69]
Could you please implement drag and drop actions for Winium.  
At the moment following error occurs when using mouseDown or any other  drag and drop commands: 

Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: 'mouseDown' is not valid or implemented command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'USER-20150617RU', ip: '192.168.2.9', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Session ID: AwesomeSession
Driver info: winium.elements.desktop.WiniumDriver
Capabilities [{debugConnectToRunningApp=false, app=C:\Users\Administrator\AppData\Local\Albelli Fotoboeken\apc.exe, platform=ANY, launchDelay=0, innerPort=9998, args=, keyboardSimulator=1}]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:33)
at org.openqa.selenium.remote.RemoteMouse.mouseDown(RemoteMouse.java:77)
at org.openqa.selenium.interactions.ClickAndHoldAction.perform(ClickAndHoldAction.java:42)
at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
at com.albumprinter.ApWebUiTest.TestApp.main(TestApp.java:93)

**Comment by congzhangzh** [comment]
will this be implement in the future?

**Comment by kumarkrish85** [comment]
Any updates? When this feature will be added in Winium?

**Comment by truptibhatt** [comment]
Any updates? @skyline-gleb

**Comment by bryanvaldellon** [comment]
Hi, hope this can be implemented.

**Comment by tharadas** [comment]
Hi all,

Is this functionality implemented ..

Thanks All

**Comment by Taldren76** [comment]
Still hoping this function is implemented.

**Comment by sravya2128** [comment]
Is Drag and drop functionality working in Winium Desktop ?
need to implement in my code but not able to do.

**Comment by DavidPurdy1** [comment]
@sravya2128 I have been looking for a similar answer and it looks like it isn't. 
It looks like you can email someone for version with drag and drop https://github.com/2gis/Winium.Desktop/issues/162
